{
 "title": "Backend Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Status backend",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{service=\"backend-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Availability ",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{service=\"backend-service\"}[1h]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "gauge",
   "description": "To compute total service availability as uptime/downtime.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "100 * (\r\n  sum(rate(flask_http_request_created{service=\"backend-service\", status=\"200\"}[5m]))\r\n  /\r\n  sum(rate(flask_http_request_created{service=\"backend-service\"}[5m]))\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!=\"200\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "HTTP requests success rate",
   "type": "timeseries",
   "description": "Counting responses not returning 200",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(sum(rate(flask_http_request_total{service=\"backend-service\", status=~\"200\"}[1h])) / sum(rate(flask_http_request_total{service=\"backend-service\"}[1h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_total[1m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\"}[30s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Number of HTTP 200 requests through the service",
   "type": "timeseries",
   "description": "To visualize the number of HTTP 200 requests through the service in a 5-minute interval\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by() (rate(flask_http_request_total{service=\"backend-service\", status=~\"200\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean service availability",
   "type": "timeseries",
   "description": "To visualize mean service availability in a 3-hour interval\n\n",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "avg_over_time((up{service=\"backend-service\"} == 1)[3h:])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Service uptime",
   "type": "timeseries",
   "description": "To see service uptime in the last 60 minutes\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum(increase(up{service=\"backend-service\"}[1h]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}