{
 "title": "Frontend metrics",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Frontend Availability",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg_over_time(nginx_up{service=\"frontend-service\"}[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Status",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "nginx_up{service=\"frontend-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP requests",
   "type": "timeseries",
   "description": "Includes all connections from users and kubesphere",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "nginx_http_requests_total{service=\"frontend-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mean request number",
   "type": "timeseries",
   "description": "Mean request normalized in the rate interval",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(nginx_http_requests_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "nginx_connections_active{service=\"frontend-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(nginx_connections_accepted{service=\"frontend-service\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}