apiVersion: v1
kind: Service
metadata:
  name: prometheus-nodeport
  namespace: kubernetes-monitoring-system
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
    prometheus: k8s
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30090  # Specifica un NodePort nel range 30000-32767
