apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1  
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker2
      containers:
        - name: backend
          image: mtdunina/backend-app:latest
          ports:
            - containerPort: 5000
          env:
            # Variabili per il database
            - name: MYSQL_HOST
              value: "mysql-service"
            - name: MYSQL_USER
              value: "root"
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: db_password
            - name: MYSQL_DB
              value: "bankdb"
            
            # Configurazioni di sicurezza
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: secret_key
            - name: USE_SSL
              value: "false"
            
            # Configurazioni aggiuntive
            - name: FLASK_ENV
              value: "production"
            - name: FLASK_DEBUG
              value: "0"
            
            # Limitazioni risorse
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "0.5"
              memory: "256Mi"
          
          # Health checks
          livenessProbe:
            httpGet:
              path: /login
              port: 5000
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz  # Usa il nuovo endpoint
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /healthz  # Usa il nuovo endpoint
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 20

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30080
  type: NodePort