apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-end
  template:
    metadata:
      labels:
        app: front-end
        monitoring: enabled  # Aggiunta per Prometheus
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker1
      containers:
        - name: front-end
          image: mtdunina/front-end:latest
          ports:
            - containerPort: 80
          env:
            - name: BACKEND_URL
              value: "http://backend-service:5000"
        - name: nginx-exporter
          image: nginx/nginx-prometheus-exporter:0.11.0
          args:
            - "--nginx.scrape-uri=http://127.0.0.1/nginx_status"
          ports:
            - containerPort: 9113

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: front-end
    monitoring: enabled  # Aggiunta per match con il ServiceMonitor
spec:
  selector:
    app: front-end
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31566
    - name: metrics
      protocol: TCP
      port: 9113
      targetPort: 9113
  type: NodePort
